# coding: utf-8

"""
    REST API for the EK80 Echo Sounder

    The API, and the documentation of it, is still under construction. Feel free to experiment with it, but Kongsberg is only able to provide very limited support at the moment.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_param_client
from ek80_param_client.api.ping_configuration_api import PingConfigurationApi  # noqa: E501
from ek80_param_client.rest import ApiException


class TestPingConfigurationApi(unittest.TestCase):
    """PingConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = ek80_param_client.api.ping_configuration_api.PingConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ping_configuration_get_channel_pulse_settings(self):
        """Test case for ping_configuration_get_channel_pulse_settings

        Get pulse settings for a specific channel  # noqa: E501
        """
        pass

    def test_ping_configuration_get_channel_transmit_power(self):
        """Test case for ping_configuration_get_channel_transmit_power

        Get transmit power for a specific channel  # noqa: E501
        """
        pass

    def test_ping_configuration_get_channels(self):
        """Test case for ping_configuration_get_channels

        Get information about all installed channels  # noqa: E501
        """
        pass

    def test_ping_configuration_set_channel_pulse_settings(self):
        """Test case for ping_configuration_set_channel_pulse_settings

        Set pulse settings for a specific channel  # noqa: E501
        """
        pass

    def test_ping_configuration_set_channel_transmit_power(self):
        """Test case for ping_configuration_set_channel_transmit_power

        Set transmit power for a specific channel  # noqa: E501
        """
        pass

    def test_ping_ek80_configuration_get_ping_configuration(self):
        """Test case for ping_ek80_configuration_get_ping_configuration

        Get adcp ping configuration  # noqa: E501
        """
        pass

    def test_ping_ek80_configuration_get_transceiver_sequencing(self):
        """Test case for ping_ek80_configuration_get_transceiver_sequencing

        """
        pass

    def test_ping_ek80_configuration_set_ping_configuration(self):
        """Test case for ping_ek80_configuration_set_ping_configuration

        Set adcp ping configuration  # noqa: E501
        """
        pass

    def test_ping_ek80_configuration_set_transceiver_sequencing(self):
        """Test case for ping_ek80_configuration_set_transceiver_sequencing

        """
        pass


if __name__ == '__main__':
    unittest.main()
