# coding: utf-8

"""
    REST API for the EK80 Echo Sounder

    The API, and the documentation of it, is still under construction. Feel free to experiment with it, but Kongsberg is only able to provide very limited support at the moment.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ek80_param_client
from ek80_param_client.api.sensors_api import SensorsApi  # noqa: E501
from ek80_param_client.rest import ApiException


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = ek80_param_client.api.sensors_api.SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sensors_add_or_update_sensor(self):
        """Test case for sensors_add_or_update_sensor

        Adds a new sensor.  # noqa: E501
        """
        pass

    def test_sensors_delete_sensor(self):
        """Test case for sensors_delete_sensor

        Deletes a sensor.  # noqa: E501
        """
        pass

    def test_sensors_get_available_sensors(self):
        """Test case for sensors_get_available_sensors

        Get list of all sensor types that can be installed.  # noqa: E501
        """
        pass

    def test_sensors_get_installed_sensors(self):
        """Test case for sensors_get_installed_sensors

        Get list of all installed sensors  # noqa: E501
        """
        pass

    def test_sensors_get_installed_sensors_full(self):
        """Test case for sensors_get_installed_sensors_full

        Get list of all sensors that are installed.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
