# coding: utf-8

"""
    REST API for setting up data subscriptions on the EK80 Echo Sounder

    The API, and the documentation of it, is still under construction. Feel free to experiment with it, but Kongsberg is only able to provide very limited support at the moment.  # How to start data output  1. Create a subscription  2. Create a communication end point  3. Add the subscription to the communication end point      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AdcpVelocitySubscriptionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_id': 'int',
        'specification': 'AdcpVelocitySubscriptionSpecification'
    }

    attribute_map = {
        'unique_id': 'unique-id',
        'specification': 'specification'
    }

    def __init__(self, unique_id=None, specification=None):  # noqa: E501
        """AdcpVelocitySubscriptionInfo - a model defined in Swagger"""  # noqa: E501

        self._unique_id = None
        self._specification = None
        self.discriminator = None

        if unique_id is not None:
            self.unique_id = unique_id
        self.specification = specification

    @property
    def unique_id(self):
        """Gets the unique_id of this AdcpVelocitySubscriptionInfo.  # noqa: E501


        :return: The unique_id of this AdcpVelocitySubscriptionInfo.  # noqa: E501
        :rtype: int
        """
        return self._unique_id

    @unique_id.setter
    def unique_id(self, unique_id):
        """Sets the unique_id of this AdcpVelocitySubscriptionInfo.


        :param unique_id: The unique_id of this AdcpVelocitySubscriptionInfo.  # noqa: E501
        :type: int
        """

        self._unique_id = unique_id

    @property
    def specification(self):
        """Gets the specification of this AdcpVelocitySubscriptionInfo.  # noqa: E501


        :return: The specification of this AdcpVelocitySubscriptionInfo.  # noqa: E501
        :rtype: AdcpVelocitySubscriptionSpecification
        """
        return self._specification

    @specification.setter
    def specification(self, specification):
        """Sets the specification of this AdcpVelocitySubscriptionInfo.


        :param specification: The specification of this AdcpVelocitySubscriptionInfo.  # noqa: E501
        :type: AdcpVelocitySubscriptionSpecification
        """
        if specification is None:
            raise ValueError("Invalid value for `specification`, must not be `None`")  # noqa: E501

        self._specification = specification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdcpVelocitySubscriptionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdcpVelocitySubscriptionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
